/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        // Wavi design system — Playful Precision
        background: '#09090d',
        surface: '#09090d',
        'surface-dim': '#06080a',
        'surface-bright': '#2a2f36',
        'surface-container-lowest': '#06080a',
        'surface-container-low': '#0e1115',
        'surface-container': '#13171b',
        'surface-container-high': '#1a1f24',
        'surface-container-highest': '#222830',
        'surface-variant': '#1e2428',
        'on-surface': '#e8ecef',
        'on-surface-variant': '#7e8f8c',
        'on-background': '#e8ecef',
        outline: '#6b7c7a',
        'outline-variant': '#252c32',
        'surface-tint': '#3de273',
        primary: '#4ff07f',
        'on-primary': '#003915',
        'primary-container': '#25d366',
        'on-primary-container': '#005523',
        secondary: '#ffb693',
        'on-secondary': '#561f00',
        'secondary-container': '#fe6b00',
        'on-secondary-container': '#572000',
        tertiary: '#cbd5df',
        'on-tertiary': '#283139',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',

        // Legacy aliases
        bg: '#09090d',
        surface2: '#222830',
        border: '#252c32',
        accent: '#4ff07f',
        accent2: '#fe6b00',
        wa: '#25d366',
        ink: '#e8ecef',
        muted: '#7e8f8c',
        danger: '#ffb4ab',
        warn: '#ffb693',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['Sora', 'system-ui', 'sans-serif'],
        sora: ['Sora', 'system-ui', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      animation: {
        'status-pulse': 'status-pulse 2s infinite',
        'neon-pulse': 'neon-pulse 2s infinite ease-in-out',
        'scan-line': 'scan-line 2.5s ease-in-out infinite',
        'spin-slow': 'spin 1.4s linear infinite',
        'slide-up': 'slide-up 0.35s ease-out both',
        'fade-in': 'fade-in 0.25s ease-out both',
      },
      keyframes: {
        'status-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.35' },
        },
        'neon-pulse': {
          '0%, 100%': { opacity: '0.7', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.06)' },
        },
        'scan-line': {
          '0%, 100%': { top: '0%' },
          '50%': { top: '100%' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      boxShadow: {
        'primary-glow': '0 0 20px rgba(79, 240, 127, 0.18)',
        'wavi-ring': '0 0 0 1px rgba(79, 240, 127, 0.2), 0 0 24px rgba(79, 240, 127, 0.12)',
        card: '0 1px 3px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.05)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.4), 0 0 0 1px rgba(79, 240, 127, 0.2)',
      },
    },
  },
  plugins: [],
}
